# Generated by Django 5.0 on 2025-12-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('family', models.CharField(help_text="The group this guest belongs to (e.g., 'Smith Family')", max_length=100)),
                ('isHeadOfFamily', models.BooleanField(default=False)),
                ('response', models.CharField(choices=[('Pending', 'Pending'), ('Attending', 'Attending'), ('Declined', 'Declined')], default='Pending', max_length=10)),
            ],
        ),
    ]
