# Generated by Django 5.0 on 2025-12-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='family',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='isHeadOfFamily',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='lastName',
        ),
        migrations.AddField(
            model_name='guest',
            name='maxGuests',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='phoneNumber',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
