# Generated by Django 5.0 on 2025-12-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp_app', '0002_remove_guest_family_remove_guest_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending_count',
            field=models.IntegerField(default=0),
        ),
    ]
