# Generated by Django 5.0 on 2025-12-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp_app', '0003_guest_attending_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id',
        ),
        migrations.AlterField(
            model_name='guest',
            name='phoneNumber',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
